const keymap = {
    id: 'TrimCardId',
    trimRef: 'TrimCardRef',
    trimTypeId: 'TrimTypeId',
    trimType: 'TrimTypeText',
    trimForRetailerId: 'TrimDevForId',
    trimForRetailer: 'TrimDevForText',
    trimFrom: 'TrimFrom',
    trimCopyFrom: 'TrimCopyFrom',
    trimManualRef: 'TrimManualRef',
    sl: 'TrimTypeSl',
    isDiscontinued: 'IsDiscontinued',
    devNo: 'TrimDevNo',
    dev: 'TrimDevText',
    description: 'TrimDes',
    size: 'TrimSize',
    composition: 'TrimComp',
    application: 'TrimApp',
    position: 'TrimPosition',
    supplierId: 'TrimSuppId',
    supplier: 'TrimSuppText',
    supplierRef: 'TrimSuppRef',
    cost: 'TrimCost',
    costCurrencyId: 'TrimCostCurrId',
    costCurrencyName: 'TrimCostCurrText',
    costCurrencySymbol: 'TrimCostCurrSym',
    remarks: 'TrimRemarks',
    createdId: 'TrimUpdatedId',
    createdBy: 'TrimUpdatedBy',
    modifiedId: 'TrimModifiedId',
    modifiedBy: 'TrimModifiedBy',
    createdDate: 'TrimUpdatedDate',
    modifiedDate: 'TrimModifiedDate',
    units: 'TrimCardUnits'
};

export { keymap as default, keymap };
/* CREATE TABLE [dbo].[TrimCard](
    --	[TrimCardId] [bigint] IDENTITY(1,1) NOT NULL,
    --	[TrimCardRef] [nvarchar](100) NOT NULL,
    --	[TrimTypeId] [nvarchar](10) NULL,
    --	[TrimTypeText] [nvarchar](250) NULL,
    --	[TrimDevForId] [nvarchar](10) NULL,
    --	[TrimDevForText] [nvarchar](250) NULL,
    --	[TrimFrom] [nvarchar](50) NULL,
    --	[TrimCopyFrom] [nvarchar](100) NULL,
    --	[TrimManualRef] [nvarchar](100) NULL,
    --	[TrimTypeSl] [int] NULL,
    --	[IsDiscontinued] [bit] NULL,
    --	[TrimDevNo] [nvarchar](10) NULL,
    --	[TrimDevText] [nvarchar](50) NULL,
    --	[TrimDes] [nvarchar](500) NULL,
    --	[TrimSize] [nvarchar](150) NULL,
    --	[TrimComp] [nvarchar](500) NULL,
    --	[TrimApp] [nvarchar](500) NULL,
    --	[TrimPosition] [nvarchar](250) NULL,
    --	[TrimSuppId] [nvarchar](10) NULL,
    --	[TrimSuppText] [nvarchar](500) NULL,
    --	[TrimSuppRef] [nvarchar](500) NULL,
    --	[TrimCost] [decimal](18, 2) NULL,
    --	[TrimCostCurrId] [nvarchar](10) NULL,
    --	[TrimCostCurrText] [nvarchar](25) NULL,
    --	[TrimCostCurrSym] [nvarchar](5) NULL,
    --	[TrimRemarks] [nvarchar](1500) NULL,
    --	[TrimUpdatedId] [nvarchar](10) NULL,
    --	[TrimUpdatedBy] [nvarchar](150) NULL,
    --	[TrimModifiedId] [nvarchar](10) NULL,
    --	[TrimModifiedBy] [nvarchar](150) NULL,
    --	[TrimUpdatedDate] [datetime] NULL,
    --	[TrimModifiedDate] [datetime] NULL,
    --	[TrimCardUnits] [varchar](500) NULL, */