const keymap = {
    id: 'TrimsID',
    sampleId: 'SampleRequestMainid',
    sampleRef: 'SampleReferenceID',
    trimType: 'TrimType',
    supplierRef: 'SupplierRef',
    description: 'TrimDescription',
    quantity: 'Quantity',
    colour: 'Colour',
    position: 'Position',
    application: 'Application',
    supplier: 'Supplier',
    price: 'Price',
    trimCardRef: 'TrimCardRef',
    trimDevNo: 'TrimDevNo',
    devNo: 'DevelopmentNo',
    sl: 'SL',
    consumption: 'Consumption',
    preTrimId: 'PreTrimsID',
    modifiedBy: 'ModifiedBy',
    modifiedDate: 'ModifiedDate',
};

export { keymap as default, keymap };
/* CREATE TABLE [dbo].[TrimsDetails](
    --	[TrimsID] [int] IDENTITY(1,1) NOT NULL,
    --	[SampleRequestMainid] [int] NOT NULL,
    --	[SampleReferenceID] [varchar](20) NULL,
    --	[TrimType] [varchar](20) NULL,
    --	[SupplierRef] [varchar](50) NULL,
    --	[TrimDescription] [varchar](50) NULL,
    --	[Quantity] [varchar](150) NULL,
    --	[Colour] [varchar](50) NULL,
    --	[Position] [varchar](50) NULL,
    --	[Application] [varchar](50) NULL,
    --	[Supplier] [varchar](50) NULL,
    --	[IsNeedtoOrder] [bit] NULL,
    --	[IsOrdered] [bit] NULL,
    --	[Price] [decimal](18, 2) NULL,
    --	[DateOrdered] [datetime] NULL,
    --	[ExSupplierDate] [datetime] NULL,
    --	[ETA] [datetime] NULL,
    --	[DateReceived] [datetime] NULL,
    --	[Leadtime]  AS (datediff(day,[DateOrdered],[DateReceived])),
    --	[ModifiedDate] [smalldatetime] NULL,
    --	[ModifiedBy] [varchar](50) NULL,
    --	[TrimMaterialType] [varchar](50) NULL,
    --	[TrimHeight] [varchar](50) NULL,
    --	[TrimWeight] [varchar](50) NULL,
    --	[TrimCad] [image] NULL,
    --	[FabricEffecttoFOB] [varchar](50) NULL,
    --	[YarnBookBy] [datetime] NULL,
    --	[InHouseBy] [datetime] NULL,
    --	[DevelopmentNo] [varchar](10) NULL,
    --	[SL] [int] NULL,
    --	[Consumption] [varchar](20) NULL,
    --	[PreTrimsID] [varchar](50) NULL,
    --	[TrimCardRef] [varchar](50) NULL,
    --	[TrimDevNo] [varchar](50) NULL, */