const keymap = {
    id: 'CadID',
    cadRef: 'CadRefferenceID',
    designer: 'Designer',
    description: 'Description',
    buyerId: 'BuyerID',
    contactPerson: 'Buyer',
    isCadSample: 'IsCadSample',
    cadStatus: 'CadStatus',
    isDiscontinue: 'IsDiscontinue',
    cadVersion: 'CadVersion',
    cadType: 'CadType',
    createdBy: 'Creator',
    createdDate: 'CreationDate',
    modifiedBy: 'ModifyBy',
    modifiedDate: 'ModificationDate',
    sl: 'SL',
    devNo: 'DevelopmentNo',
    department: 'Department',
    requestOption: 'RequestOption',
    oldRef: 'OldRefferenceID',
    shape: 'shape',
    shapeDes: 'shapedes',
    baseColour: 'basecolour',
    printTec: 'printtec',
    licensor: 'licensor',
    cadApproval: 'cadapproval',
    cadCollection: 'CadCollection',
    remarks: 'Note',
    cadAvailability: 'CadAvaility',
    isOrder: 'IsOrder',
    isCancel: 'IsCancel',
    cadUploadTypeText: 'CadUploadTypeText',
    cadUploadTypeId: 'CadUploadTypeId',
    boughtRef: 'BoughtRef',
};

export { keymap as default, keymap };
/* CREATE TABLE [dbo].[CadRequestMain](
	[CadID] [bigint] IDENTITY(1,1) NOT NULL,
	[CadRefferenceID] [varchar](50) NULL,
	[Designer] [int] NULL,
	[Description] [varchar](350) NULL,
	[BuyerID] [int] NULL,
	[Buyer] [varchar](50) NULL,
	[IsCadSample] [bit] NULL,
	[CadStatus] [varchar](10) NULL,
	[IsDiscontinue] [bit] NULL,
	[CadVersion] [int] NULL,
	[CadType] [varchar](10) NULL,
	[Creator] [varchar](50) NULL,
	[CreationDate] [datetime] NULL,
	[ModifyBy] [varchar](50) NULL,
	[ModificationDate] [datetime] NULL,
	[SL] [bigint] NULL,
	[DevelopmentNo] [varchar](10) NULL,
	[Department] [varchar](10) NULL,
	[RequestOption] [varchar](10) NULL,
	[OldRefferenceID] [varchar](50) NULL,
	[shape] [varchar](150) NULL,
	[shapedes] [varchar](350) NULL,
	[basecolour] [varchar](50) NULL,
	[printtec] [varchar](10) NULL,
	[licensor] [varchar](10) NULL,
	[cadapproval] [varchar](10) NULL,
	[CadCollection] [varchar](3) NULL,
	[Note] [varchar](1000) NULL,
	[CadAvaility] [varchar](3) NULL,
	[IsOrder] [bit] NULL,
	[IsCancel] [bit] NULL,
	[CadUploadTypeText] [varchar](150) NULL,
	[CadUploadTypeId] [tinyint] NULL,
	[BoughtRef] [varchar](50) NULL, */