const keymap = {
    id: 'FabricID',
    sampleId: 'SampleRequestMainid',
    sampleRef: 'SampleReferenceID',
    fabricType: 'FabricType',
    composition: 'Composition',
    gsm: 'FinishedGSM',
    dyeType: 'DyeType',
    specialFabricRef: 'SpecialFabricRef',
    finishWash: 'SpecialFinish',
    colour: 'FabricColour',
    eld: 'ELD',
    fabricParts: 'FabricFor',
    devNo: 'DevelopmentNo',
    sl: 'SL',
    fabricFrom: 'FabFrom',
    preFabricId: 'PreFabricID',
    isTc: 'istc',
    tc: 'TcText',
};

export { keymap as default, keymap };
/* CREATE TABLE [dbo].[FabricDetails](
    --	[FabricID] [bigint] IDENTITY(1,1) NOT NULL,
    --	[SampleReferenceID] [varchar](50) NOT NULL,
    --	[FabricType] [varchar](10) NULL,
    --	[Composition] [varchar](10) NULL,
    --	[FinishedGSM] [varchar](10) NULL,
    --	[DyeType] [varchar](10) NULL,
    --	[SpecialFabricRef] [varchar](max) NULL,
    --	[SpecialFinish] [varchar](10) NULL,
    --	[FabricColour] [varchar](200) NULL,
    --	[ELD] [varchar](100) NULL,
    --	[FabricFor] [varchar](10) NULL,
    --	[IsDischargeable] [bit] NULL,
    --	[IsYDS] [bit] NULL,
    --	[IsEngineeredStripe] [bit] NULL,
    --	[SampleRequestMainid] [int] NULL,
    --	[FabricEffecttoFOB] [varchar](50) NULL,
    --	[YarnBookBy] [datetime] NULL,
    --	[InHouseBy] [datetime] NULL,
    --	[DevelopmentNo] [varchar](10) NULL,
    --	[SL] [int] NULL,
    --	[FabFrom] [varchar](250) NULL,
    --	[YarnCount] [varchar](5) NULL,
    --	[Consumption] [varchar](20) NULL,
    --	[PreFabricID] [varchar](50) NULL,
    --	[istc] [bit] NULL,
    --	[TcText] [varchar](50) NULL, */